# Generated by Django 5.2.17 on 2026-09-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('business_category', models.CharField(blank=True, max_length=255)),
                ('service_area', models.CharField(blank=True, max_length=100)),
                ('business_maturity', models.CharField(blank=True, max_length=100)),
                ('offering_type', models.CharField(blank=True, max_length=100)),
                ('ticket_size', models.CharField(blank=True, max_length=100)),
                ('primary_goal', models.CharField(blank=True, max_length=100)),
                ('acquisition_channel', models.CharField(blank=True, max_length=100)),
                ('existing_assets', models.JSONField(blank=True, default=list)),
                ('current_problem', models.CharField(blank=True, max_length=100)),
                ('ad_experience', models.CharField(blank=True, max_length=100)),
                ('budget_range', models.CharField(blank=True, max_length=100)),
                ('urgency', models.CharField(blank=True, max_length=100)),
                ('lead_score_intent', models.PositiveIntegerField(default=0)),
                ('lead_score_budget', models.PositiveIntegerField(default=0)),
                ('lead_score_urgency', models.PositiveIntegerField(default=0)),
                ('lead_score_service_fit', models.PositiveIntegerField(default=0)),
                ('recommended_primary', models.CharField(blank=True, max_length=255)),
                ('recommended_secondary', models.CharField(blank=True, max_length=255)),
                ('consultant_rationale', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
